### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by briusxD** [PhantomDevelopmentMC/PhantomVoting#5]
[13:03:41] [Craft Scheduler Thread - 407/WARN]: [PhantomVoting] Plugin PhantomVoting v1 generated an exception while executing task 15910
java.lang.NoSuchMethodError: 'int org.bukkit.Server.broadcast(net.kyori.adventure.text.Component)'
	at me.fergs.phantomvoting.managers.MessageManager.lambda$broadcastMessage$4(MessageManager.java:132) ~[?:?]
	at java.util.Collections$SingletonList.forEach(Collections.java:4966) ~[?:?]
	at me.fergs.phantomvoting.managers.MessageManager.broadcastMessage(MessageManager.java:130) ~[?:?]
	at me.fergs.phantomvoting.inventories.LeaderboardInventory.refreshLeaderboardData(LeaderboardInventory.java:114) ~[?:?]
	at me.fergs.phantomvoting.inventories.LeaderboardInventory.access$000(LeaderboardInventory.java:23) ~[?:?]
	at me.fergs.phantomvoting.inventories.LeaderboardInventory$1.run(LeaderboardInventory.java:105) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1.jar:3871-Spigot-d2eba2c-3f9263b]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.20.1.jar:3871-Spigot-d2eba2c-3f9263b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Fergs32** [comment]
What version are you tunning this on, and what platform are you using? (spigot, paper, sponge)

**Comment by briusxD** [comment]
I use 1.21.1 spigot and it was working fine in 1.20 paper but I had to change it, every plugin passed without any problems but your plugin did not
